
<p class="small" style="text-align: right">
	We use Source Forge to mirror some of our bigger downloads.
	<a href="http://sourceforge.net/projects/thousandparsec/">
		<img style="vertical-align: middle" src="http://sourceforge.net/sflogo.php?group_id=132078&amp;type=3" width="63" height="19" alt="SourceForge.net Logo" />
	</a>
</p><p class="small" style="text-align: center">
	Thousand Parsec, TP and the golden wreath logo are all trademarks of, MITHIS in 
	Australia and Lee Begg in New Zealand. Some rights reserved.
</p>

</body>
</html>
