<div id="footer">
Web Design Copyright (c) <a href="http://riyonuk.no-ip.org/">Donovan &quot;Riyonuk&quot; Hernandez</a> - 
<a href="http://validator.w3.org/check/referer">XHTML</a> -
<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a><br />
Thousand Parsec, TP and the golden wreath logo are all trademarks of, MITHIS in Australia and Lee Beggs in New Zealand. Some rights reserved
</div>

</div><!-- End wrapper -->
</body></html>
