<html>
<head>

<title>
	Thousand Parsec:<?php echo $title ?>
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<style type="text/css">
<!--
a {  font-family: "Times New Roman", Times, serif; color: #00FF99; text-decoration: none}
-->
</style>

</head>

<body bgcolor="#000000" text="#FFFFFF" background="/tp/graphics/background.jpg" link="#00CCCC" vlink="#FFCC99">

<div align="center"> 
	<p>
		<font color="#FFFFFF" face="Arial, Helvetica, sans-serif" size="7">
			Thousand Parsec
		</font><br>
    		<font color="#FFFFFF" face="Arial, Helvetica, sans-serif" size="2">
			A journey of a thousand parsec starts with a single step
		</font>
	</p>
</div>


<table width="100%" border="0" bordercolor="#FFFFFF">
	<tr> 
		<td bgcolor="#000000" align="center">
			<a href="/tp/index.php">
				NEWS
			</a>
		</td>
		<td bgcolor="#000000" align="center">
			<a href="/tp/about.php">
				ABOUT
			</a>
		</td>
		<td bgcolor="#000000" align="center">
			<a href="/tp/documents.php">
				DOCUMENTS
			</a>
		</td>
		<td bgcolor="#000000" align="center">
			<a href="/tp/downloads.php">
				DOWNLOADS
			</a>
		</td>
		<td bgcolor="#000000" align="center">
			<a href="/tp/dev/index.php">
				DEVELOPERS
			</a>
		</td>
		<td bgcolor="#000000" align="center">
			<a href="/tp/faq.php">
				FAQ
			</a>
		</td>
		<td bgcolor="#000000" align="center">
			<a href="/tp/links.php">
				LINKS
			</a>
		</td>
	</tr>
</table>
<br>

