<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>

<title>
	Thousand Parsec:<?php echo $title ?>
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="StyleSheet" href="/tp/style.css" type="text/css">

</head>
<body>

<div id="header_main">Thousand Parsec</div>
<div id="header_quote">A journey of a thousand parsec starts with a single step</div>

<table class="menu">
	<tr> 
		<td>
			<a href="/tp/gettingstarted.php"><b>Getting Started</b></a>
		</td><td>
			<a href="/tp/index.php">News</a>
			<a href="/tp/rss.php"><img src="/tp/graphics/rss.gif" width=18 height=7 border=0 alt="[XML]"></a>
		</td><td>
			<a href="/tp/about.php">About</a>
		</td><td>
			<a href="/tp/screenshots.php">Screenshots</a>
		</td><td>
			<a href="/tp/documents.php">Documents</a>
		</td><td>
			<a href="/tp/downloads.php">Downloads</a>
		</td><td>
			<a href="/tp/dev/index.php">Developers</a>
		</td><td>
			<a href="/tp/faq.php">FAQ</a>
		</td><td>
			<a href="/tp/mailman.php/listinfo/">Lists</a>
		</td><td>
			<a href="http://www.thousandparsec.net/forums/">Forums</a>
		</td><td>
			<a href="/tp/links.php">Links</a>
		</td>
	</tr>
</table>
